(dp1
S'output'
p2
S'<class \'gluon.contrib.pymysql.err.InternalError\'> (1050, u"Table \'auth_user\' already exists")'
p3
sS'layer'
p4
S'/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/applications/StuffShare/models/db.py'
p5
sS'code'
p6
S"# db = DAL('mysql://clan10:clan10@clan10.pythonanywhere.com/mysql.server/clan10$stuffshare')\ndb = DAL('mysql://clan10:clan10@localhost:3306/stuffshare')\nfrom gluon.tools import Auth\nauth = Auth(db)\nauth.define_tables(username=False,signature=False)\n\nauth.settings.actions_disabled.append('request_reset_password')\nauth.settings.actions_disabled.append('retrieve_username')\n\n\ndb.define_table('posessions',\n    Field('id', 'integer', unique=True, requires=[IS_NOT_EMPTY(), IS_ALPHANUMERIC()]),\n    Field('user_id', 'integer', requires=[IS_NOT_EMPTY(), IS_IN_DB(db, db.auth_user.id)]),\n    Field('item_name', 'text', requires=[IS_NOT_EMPTY()]),\n    Field('notes', 'text', requires=[IS_NOT_EMPTY()]),\n    Field('quality', 'text', requires=[IS_NOT_EMPTY()]),\n    Field('return_date', 'date', requires=[IS_NOT_EMPTY()]),\n    Field('picture', 'upload'))\n\ndb.posessions.quality.requires=IS_IN_SET(('Poor','Mediocre','Average', 'Good', 'Excellent', 'Like New'))\ndb.posessions.id.readable = False\ndb.posessions.user_id.readable = False\n\n#\n# db.define_table('friends',\n#     Field('id', 'integer', unique=True, requires=[IS_NOT_EMPTY(), IS_ALPHANUMERIC()]),\n#     Field('user_id', 'integer', db.auth_user, requires=[IS_NOT_EMPTY(), IS_ALPHANUMERIC(), IS_IN_DB(db, db.auth_user.id)]),\n#     Field('friend_id', 'integer', db.auth_user, requires=[IS_NOT_EMPTY(), IS_ALPHANUMERIC(), IS_IN_DB(db, db.auth_user.id)]))\n#\n# db.friends.id.readable = False\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/gluon/restricted.py", line 224, in restricted\n    exec ccode in environment\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/applications/StuffShare/models/db.py", line 5, in <module>\n    auth.define_tables(username=False,signature=False)\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/gluon/tools.py", line 1875, in define_tables\n    format=\'%(first_name)s %(last_name)s (%(id)s)\'))\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/gluon/dal.py", line 8414, in define_table\n    table = self.lazy_define_table(tablename, *fields, **args)\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/gluon/dal.py", line 8450, in lazy_define_table\n    polymodel=polymodel)\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/gluon/dal.py", line 1107, in create_table\n    self.create_sequence_and_triggers(query, table)\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/gluon/dal.py", line 1949, in create_sequence_and_triggers\n    self.execute(query)\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/gluon/dal.py", line 1967, in execute\n    return self.log_execute(*a, **b)\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/gluon/dal.py", line 1961, in log_execute\n    ret = self.cursor.execute(command, *a[1:], **b)\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/gluon/contrib/pymysql/cursors.py", line 117, in execute\n    self.errorhandler(self, exc, value)\n  File "/Users/IshanB/Documents/Developer/pyCharm/StuffShare/web2py/gluon/contrib/pymysql/connections.py", line 202, in defaulterrorhandler\n    raise errorclass, errorvalue\nInternalError: (1050, u"Table \'auth_user\' already exists")\n'
p11
s.